ALTER TABLE players ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ittf_id INTEGER;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ittf_data JSONB;
ALTER TABLE players ADD COLUMN IF NOT EXISTS ittf_last_synced TIMESTAMPTZ;
